<script>
    let generator = '/ultrasonicSignalGenerator.jpg';
</script>

<div id="page">
    <h1>Alpha Prototype</h1>
    <hr/>
    <div class="paragraph">
        <p>The alpha prototype will feature all components of the design; however, they will not yet be fully functional. The ultrasonic signal will be produced by the signal generator shown in Figure 19 below, which is powered by a rechargeable 9V battery. The signal generator can produce signals ranging from 1Hz to 1MHz, which will allow the correct frequency and intensity to be chosen for the treatment and optimize the amount of BGS the patient is receiving.</p>
        <img src={generator} alt="Signal generated by BGS circuit">
        <p>The signal will be transmitted through a sound wave using a piezo transducer 25mm in diameter capable of handling up to 1MHz frequency. This transducer will be attached to the elastic strap. The method in which the transducer will be attached to the strap is still being decided and will be incorporated in the beta prototype. To test the EMS, we ordered an at home EMS machine to gain insight on how the electric impulses are formed and sent to the electrodes. For our alpha prototype we will use this machine to model how the electrodes are going to be connected to the elastic strap. The wires will pass through the elastic material and will be able to extend out to reach either end of the muscle that requires therapy.</p>
        <p>The strap will be comprised of two layers of elastic material sewn together to hold the transducer and wiring between them. A small strip of Velcro will be sewn on either end of the strap which will tighten the strap around the patient. The battery pack housing was 3D printed to show how the strap would interact with the box. For the beta prototype the size of the housing will need to be reduced and the components will have to be rearranged to optimize the usage of space. The battery pack will be able to clip onto the patient’s waistband, so a clip must be designed to attach onto the back panel of the housing. A clip was included in the original design, but it was unable to be robustly printed, so a separate clip must be designed or purchased.</p>
    </div>

</div>


<style>
	h1{
	   font-family: "Readex Pro Variable", sans-serif;
	   font-weight: 500;
	   margin-bottom: 0%;
   }
   #page{
	margin-top: 65px;
	margin-left: 15%;
	margin-right: 15%;
    padding-bottom: 15%;
   }
   .paragraph{
	text-indent: 5%;
   }
   hr{
        border-top: 2px solid #194AA4;
        border-radius: 1px;
        padding: 0%;
    }
    .subsection{
        border-top: 2px solid #699BF7;
        border-radius: 1px;
        padding: 0%;
    }
</style>