<script>
    let signal = '/signalGeneratedByBGSCircuit.jpg';
    let box1 = '/firstIteration.jpg';
    let box2 = '/secondIteration.jpg';
    let box3 = '/thirdIteration.jpg';
    let ring = '/solidworksModelOfTransducerRing.jpg';
    let strapBack = '/backSurfaceOfStrap.jpg';
    let strapFront = '/frontSurfaceOfStrap.jpg';
    let diagram = '/systemsDiagram.jpg';
    let wave = '/ultrasonicSineWave.jpg';
    let product = '/deviceWithAllComponentsConnected.jpg'
</script>

<div id="page">
    <h1>Beta Prototype</h1>
    <hr/>
    <div class="paragraph">
        <p>Utilizing a signal generator the BGS circuit was assembled to emit ultrasonic signals powered by a rechargeable 9V battery. The signal generator offers a wide frequency range, from 1Hz to 1MHz, enabling precise selection of frequency and intensity for optimized BGS treatment delivery. Employing a 25mm diameter piezo transducer, the circuit converts the signal into ultrasonic pulses, pivotal for therapeutic efficacy.</p>
        <p>Despite successful signal generation, further testing revealed discrepancies in the transducer's response, necessitating adjustments for optimal functionality. Specifically, the need for a square wave signal was identified, requiring programming modifications to the Arduino board to regulate the signal output from the circuit. This iterative process underscores the project's commitment to precision and effectiveness in therapeutic delivery. </p>
        <p>To gain insight into the generation and control of electrical pulses, an existing EMS device was purchased initially, with the intention of repurposing its circuitry to suit our device's requirements. However, upon review, it was deemed more advantageous to construct a new circuit from scratch, affording greater control over signal parameters. The circuit diagram has been finalized, awaiting the arrival of necessary components to commence construction.</p>
        <img src={signal} alt="Signal generated by BGS circuit">
    </div>
    <h2>Circuitry Housing</h2>
    <hr class="subsection"/>
    <div class="paragraph">
        <p>Substantial enhancements were made to the original circuitry box compared to its previous iteration. Primarily, its size was optimized to accommodate components snugly, eliminating unnecessary bulkiness. Design modifications, including filleting corners and adjusting geometry, were implemented to streamline the 3D printing process and minimize the need for support material. Internal fasteners were integrated to secure components, mitigating potential circuit damage during use. Furthermore, the removal of the clip was deemed necessary to enhance portability, while redesigned wire cutouts facilitate seamless connection of circuits to the strap, enhancing overall usability and functionality.</p>
        <img src={box1} alt="First Iteration">
        <img src={box2} alt="Second Iteration">
        <img src={box3} alt="Third Iteration">
    </div>
    <h2>Device Improvements</h2>
    <hr class="subsection"/>
    <div class="paragraph">
        <p>The other design component of the product that was modified from the alpha prototype was the connection between the transducer and strap that attached to the patient. Using SolidWorks, we designed a plastic ring that holds the transducer in place. It creates a secure connection between the transducer and the strap to ensure no movement of the transducer during treatment. This ring also creates a flat surface to be strapped to the body for increased comfort of the patients. In future phases the transducer will be permanently secured but as of now it still needs to be able to be removed for more testing, so it is only a temporary connection. </p>
        <img src={ring} alt="SolidWorkds model of transducer ring">
        <p>Shown below are both the front and back surfaces of the strap with both the transducer and transducer ring installed. The transducer ring was printed using PLA filament on Bambu Labs X1 Carbon printers and attached to the strap using hot glue. In the future the ring may be sewn into the strap to ensure a more secure connection. </p>
        <img src={strapBack} alt="Back of the strap with transducer ring">
        <img src={strapFront} alt="Front of the strap with transducer ring">
    </div>
    <h2>Testing</h2>
    <hr class="subsection"/>
    <div class="paragraph">
        <p>To test the electrical systems of our design we first started by making a systems diagram to separate it into different components. The two major components of the mechanical system were the EMS and BGS circuit. As described in the alpha prototype testing, we were able to receive the correct sine wave at approximately 1MHz required for bone growth from the ultrasonic signal generator.</p>
        <img src={diagram} alt="Systems Diagram">
        <p>In the testing of the beta prototype, we also were able to determine how to correctly pulse the ultrasonic signal to receive the desired low intensity pulsed ultrasound stimulation (LIPUS). The sine wave must be pulsed at approximately 1kHz to ensure effective bone growth stimulation. Using both the Arduino board and a MOSFET we were able to pulse this signal.  The results of this signal were tested on the oscilloscope and shown below.</p>
        <img src={wave} alt="Ultrasonic Sine Wave">
        <p>When the signal shown above is sent to the piezoelectric transducer it vibrates it at the correct frequency for bone growth. Using ultrasonic gel on the surface of the body the signal does not get reflected off the skin and is able to penetrate through to the bone to promote growth.</p>
        <img src={product} alt="Completed Beta Prototype connected to a patient">
        <p>Shown above is the final beta prototype for our device, there are still improvements and future testing to be done in phase 5. The fabrication of the physical components of our device was done using 3D printing. To print all components which includes the circuitry box and the transducer ring, the overall print time is just under 4 hours using under 60m of filament. In future phases we will be optimizing all 3D printed components to reduce the total manufacturing time and amount of product used. The electrical components will be soldered together to ensure more secure connection between components. Soldering can be time consuming which will increase the manufacturing time and costs, but it will lead to a better final product.</p>
    </div>


</div>


<style>
	h1{
	   font-family: "Readex Pro Variable", sans-serif;
	   font-weight: 500;
	   margin-bottom: 0%;
   }
   #page{
	margin-top: 65px;
	margin-left: 15%;
	margin-right: 15%;
    padding-bottom: 15%;
   }
   .paragraph{
	text-indent: 5%;
   }
   hr{
        border-top: 2px solid #194AA4;
        border-radius: 1px;
        padding: 0%;
    }
    .subsection{
        border-top: 2px solid #699BF7;
        border-radius: 1px;
        padding: 0%;
    }
</style>